In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/extrovert-vs-introvert-behavior-data/personality_dataset.csv


In [2]:
#closs warning
def warn(*ards, **kwargs):
    pass
import warnings
warnings.warn = warn

In [3]:
df = pd.read_csv("/kaggle/input/extrovert-vs-introvert-behavior-data/personality_dataset.csv", header=0)
df

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()


Time_spent_Alone Stage_fear  Social_event_attendance  Going_outside  \
0                  4.0         No                      4.0            6.0   
1                  9.0        Yes                      0.0            0.0   
2                  9.0        Yes                      1.0            2.0   
3                  0.0         No                      6.0            7.0   
4                  3.0         No                      9.0            4.0   
...                ...        ...                      ...            ...   
2895               3.0         No                      7.0            6.0   
2896               3.0         No                      8.0            3.0   
2897               4.0        Yes                      1.0            1.0   
2898              11.0        Yes                      1.0            NaN   
2899               3.0         No                      6.0            6.0   

     Drained_after_socializing  Friends_circle_size  Post_frequency  \
0                           No                 13.0             5.0   
1                          Yes                  0.0             3.0   
2                          Yes                  5.0             2.0   
3                           No                 14.0             8.0   
4                           No                  8.0             5.0   
...                        ...                  ...             ...   
2895                        No                  6.0             6.0   
2896                        No                 14.0             9.0   
2897                       Yes                  4.0             0.0   
2898                       Yes                  2.0             0.0   
2899                        No                  6.0             9.0   

     Personality  
0      Extrovert  
1      Introvert  
2      Introvert  
3      Extrovert  
4      Extrovert  
...          ...  
2895   Extrovert  
2896   Extrovert  
2897   Introvert  
2898   Introvert  
2899   Extrovert  

[2900 rows x 8 columns]

In [4]:
df.groupby("Personality").count()

Time_spent_Alone  Stage_fear  Social_event_attendance  \
Personality                                                          
Extrovert                1457        1449                     1463   
Introvert                1380        1378                     1375   

             Going_outside  Drained_after_socializing  Friends_circle_size  \
Personality                                                                  
Extrovert             1456                       1473                 1451   
Introvert             1378                       1375                 1372   

             Post_frequency  
Personality                  
Extrovert              1458  
Introvert              1377

## Preprocessing

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2900 entries, 0 to 2899
Data columns (total 8 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   Time_spent_Alone           2837 non-null   float64
 1   Stage_fear                 2827 non-null   object 
 2   Social_event_attendance    2838 non-null   float64
 3   Going_outside              2834 non-null   float64
 4   Drained_after_socializing  2848 non-null   object 
 5   Friends_circle_size        2823 non-null   float64
 6   Post_frequency             2835 non-null   float64
 7   Personality                2900 non-null   object 
dtypes: float64(5), object(3)
memory usage: 181.4+ KB


In [6]:
df.isnull().sum()

Time_spent_Alone             63
Stage_fear                   73
Social_event_attendance      62
Going_outside                66
Drained_after_socializing    52
Friends_circle_size          77
Post_frequency               65
Personality                   0
dtype: int64

In [7]:
df_clean = df.dropna()
df_clean.isnull().sum()

Time_spent_Alone             0
Stage_fear                   0
Social_event_attendance      0
Going_outside                0
Drained_after_socializing    0
Friends_circle_size          0
Post_frequency               0
Personality                  0
dtype: int64

In [8]:
df_clean.groupby("Personality").count()

Time_spent_Alone  Stage_fear  Social_event_attendance  \
Personality                                                          
Extrovert                1274        1274                     1274   
Introvert                1203        1203                     1203   

             Going_outside  Drained_after_socializing  Friends_circle_size  \
Personality                                                                  
Extrovert             1274                       1274                 1274   
Introvert             1203                       1203                 1203   

             Post_frequency  
Personality                  
Extrovert              1274  
Introvert              1203

ข้อมูลค่อนข้าง balance

In [9]:
# convert type
str_col = ['Stage_fear', 'Drained_after_socializing', 'Personality']
for item in str_col:
    df_clean[item] = pd.factorize(df_clean[item])[0]
df_clean

Time_spent_Alone  Stage_fear  Social_event_attendance  Going_outside  \
0                  4.0           0                      4.0            6.0   
1                  9.0           1                      0.0            0.0   
2                  9.0           1                      1.0            2.0   
3                  0.0           0                      6.0            7.0   
4                  3.0           0                      9.0            4.0   
...                ...         ...                      ...            ...   
2892               9.0           1                      2.0            0.0   
2895               3.0           0                      7.0            6.0   
2896               3.0           0                      8.0            3.0   
2897               4.0           1                      1.0            1.0   
2899               3.0           0                      6.0            6.0   

      Drained_after_socializing  Friends_circle_size  Post_frequency  \
0                             0                 13.0             5.0   
1                             1                  0.0             3.0   
2                             1                  5.0             2.0   
3                             0                 14.0             8.0   
4                             0                  8.0             5.0   
...                         ...                  ...             ...   
2892                          1                  1.0             2.0   
2895                          0                  6.0             6.0   
2896                          0                 14.0             9.0   
2897                          1                  4.0             0.0   
2899                          0                  6.0             9.0   

      Personality  
0               0  
1               1  
2               1  
3               0  
4               0  
...           ...  
2892            1  
2895            0  
2896            0  
2897            1  
2899            0  

[2477 rows x 8 columns]

In [10]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2477 entries, 0 to 2899
Data columns (total 8 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   Time_spent_Alone           2477 non-null   float64
 1   Stage_fear                 2477 non-null   int64  
 2   Social_event_attendance    2477 non-null   float64
 3   Going_outside              2477 non-null   float64
 4   Drained_after_socializing  2477 non-null   int64  
 5   Friends_circle_size        2477 non-null   float64
 6   Post_frequency             2477 non-null   float64
 7   Personality                2477 non-null   int64  
dtypes: float64(5), int64(3)
memory usage: 174.2 KB


## Split Xall , yall

In [11]:
# แยก features (X) และ target (y)
Xall = df_clean.drop(['Personality'], axis=1).values
yall = df_clean['Personality'].values

In [12]:
print("Xall Shape", Xall.shape, "feature ที่ใช้เป็น input ในโมเดล drop 1 เหลือ 7") 
print("yall Shape",yall.shape, "target หรือ label ที่ต้องการพยากรณ์ // ตัวแปร yall ให้เก็บค่าจากคอลัมน์ 'Personality'")

Xall Shape (2477, 7) feature ที่ใช้เป็น input ในโมเดล drop 1 เหลือ 7
yall Shape (2477,) target หรือ label ที่ต้องการพยากรณ์ // ตัวแปร yall ให้เก็บค่าจากคอลัมน์ 'Personality'


In [13]:
[sum(yall==1), sum(yall==0)] #sum num of 1 = Extrovert, 0 = Introvert

[1203, 1274]

## Train Test Spilt

In [14]:
from sklearn.model_selection import train_test_split
X, Xt, y, yt = train_test_split(Xall, yall, test_size=0.25, random_state=0)

In [15]:
[sum(y==1), sum(y==0), sum(yt==1), sum(yt==0)]

[907, 950, 296, 324]

## Normalization

In [16]:
#Normalization ให้เป็น 1 กับ 0

from sklearn.preprocessing import MinMaxScaler
scl = MinMaxScaler().fit(X)
X = scl.transform(X)
Xt = scl.transform(Xt)

In [17]:
np.max(X,axis=0), np.min(X, axis=0)

(array([1., 1., 1., 1., 1., 1., 1.]), array([0., 0., 0., 0., 0., 0., 0.]))

In [18]:
np.max(Xt, axis=0)

array([1., 1., 1., 1., 1., 1., 1.])

In [19]:
np.unique(y)  #2 class : 0,1

array([0, 1])

## Model

#### Calculate Only Test Accuracy

In [20]:
from sklearn.svm import SVC
clf = SVC(random_state=1)
clf.fit(X,y) # คำสั่ง train model ; fit()

SVC(random_state=1)

In [21]:
yp = clf.predict(Xt) # ทำนาย แล้วเก็บไว้ใน yp

In [22]:
sum(yt==yp)/len(yt)  #วัดเปอร์เซ็นความแม่น %

0.9225806451612903

#### Using **Hold-Out** for  1. calculate **Training Accuracy**

In [23]:
# Divide Train-Validation-Test // Hove out - Best Split แบ่งข้อมูลเป็น 80% ฝึก, 20% ทดสอบ

from sklearn.model_selection import train_test_split
X, Xt, y, yt = train_test_split(Xall, yall, test_size=0.2, random_state=0)
X, Xv, y, yv = train_test_split(X, y, test_size=0.25, random_state=0)

In [24]:
[len(y), len(yv), len(yt)]

[1485, 496, 496]

In [25]:
from sklearn.svm import SVC
clf = SVC(random_state=1)
clf.fit(X,y)
yp = clf.predict(Xv)
sum(yv==yp)/len(yv)

0.9435483870967742

#### 2. Calculate **Test Accuracy**

In [26]:
clf = SVC(random_state=1,C=1)
clf.fit(X,y)
yp = clf.predict(Xt)
sum(yt==yp)/len(yt)

0.9354838709677419

#### Using **5CV** for  1. calculate **Training Accuracy**

In [27]:
# Divide Train-Test
from sklearn.model_selection import train_test_split
X, Xt, y, yt = train_test_split(Xall, yall, test_size=0.25, random_state=0)

In [28]:
from sklearn.model_selection import cross_val_predict
from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier(random_state=0)
yp = cross_val_predict(clf, X, y, cv=5)
sum(yp==y)/len(y) # Training Accuacy

0.8589122240172321

#### 2. Calculate **Test Accuracy**

In [29]:
clf =  DecisionTreeClassifier(random_state=0)
clf.fit(X,y)
yp = clf.predict(Xt)
sum(yt==yp)/len(yt)

0.853225806451613

#### **Grid-Search** Tune Model using **Cross Validation**

In [30]:
# Divide Train-Test
from sklearn.model_selection import train_test_split
X, Xt, y, yt = train_test_split(Xall, yall, test_size=0.25, random_state=0)

In [31]:
# Training Accuracy
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC

params ={ 'C': [1,2,4,8] }
clf = GridSearchCV( SVC(random_state =0), params, cv=2).fit(X,y)

# Training Accuracy and Parameters
[clf.best_score_, clf.best_params_]

[0.9262271027430311, {'C': 1}]

In [32]:
# Test Accuracy
yp = clf.best_estimator_.predict(Xt)
sum(yp==yt)/len(yt)

0.9225806451612903